### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mashhoorahdal**
Edited README.md regarding compilation of lex

### CODE REVIEW

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
@mashhoor-ahdal thanks for your interest in contributing! but, why would you prefer `gcc` over `cc`?

**Comment by mashhoorahdal** [comment]
> @mashhoor-ahdal thanks for your interest in contributing! but, why would you prefer `gcc` over `cc`?

Oh , I see... Sorry for the inconvenience

**Comment by VishnuSanal** [comment]
> > @mashhoor-ahdal thanks for your interest in contributing! but, why would you prefer `gcc` over `cc`?
> 
> Oh , I see... Sorry for the inconvenience

um... I didn't mean to demotivate, apologies if that sounded so. rather I was wondering the reason/advantage for using `gcc`!

**Comment by mashhoorahdal** [comment]
> > > @mashhoor-ahdal thanks for your interest in contributing! but, why would you prefer `gcc` over `cc`?
> > 
> > 
> > Oh , I see... Sorry for the inconvenience
> 
> um... I didn't mean to demotivate, apologies if that sounded so. rather I was wondering the reason/advantage for using `gcc`!

ok no worries, there is no advantage btw

**Pull request closed without merging**
